apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: "{{ .Values.rayjob.name }}"
  namespace: "{{ .Values.rayjob.namespace }}"
spec:
  entrypoint: python -c "import ray; ray.init(); print('Hello World')"
  shutdownAfterJobFinishes: true
  rayClusterSpec:
    rayVersion: "{{ default .Chart.AppVersion .Values.image.tag }}"
    headGroupSpec:
      rayStartParams: {}
      template:
        spec:
          containers:
            - name: ray-head
              image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
    workerGroupSpecs:
      - replicas: 1
        groupName: workergroup
        rayStartParams: {}
        template:
          spec:
            containers:
              - name: ray-worker
                image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
